Vary the size of the inputs for the benchmarks
andrewhalle/primes pull request #9
Opened 2022-08-10 04:32 UTC by bowlofeggs

Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

2022-08-10 19:34 UTC, bowlofeggs commented on benches/all.rs
> +    for i in [10_000, 100_000, 1_000_000, 10_000_000, 100_000_000, 500_000_000].iter() {
Running all of these does take hours, but I've confirmed that you can ask at the CLI to run a subset of them pretty easily.

e.g., you can ask for a specific test like this:

```
$ cargo bench -- live_first_prime/1000000\$
```

Or, you can run all the 10k ones like this:

```
$ cargo bench -- 10000\$
```

2022-08-11 01:04 UTC, andrewhalle requested changes
One minor thing

2022-08-11 01:04 UTC, andrewhalle commented on benches/all.rs
> +    // For each tuple, the first number is the largest prime number we will search for for
Is this comment still applicable? It mentions tuples, which I don't see.

2022-08-11 01:06 UTC, andrewhalle commented on benches/all.rs
> +    // For each tuple, the first number is the largest prime number we will search for for
I think this comment is pre-`Input` so might be better phrased as "Each number in this list defines a search space in which we will record the largest prime and the index of that prime" or similar

2022-08-11 01:08 UTC, andrewhalle requested changes

2022-08-11 01:08 UTC, andrewhalle commented on benches/all.rs
> +criterion_group!(all, bench_em,);
Doesn't hurt anything, but I think the trailing comma can be removed as well, that's how this macro appears in the criterion docs.

2022-08-11 21:09 UTC, andrewhalle approved these changes

2022-08-11 21:10 UTC, merged